index/urls.py
from django.urls import path

from . import views


app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:health_id>/', views.lists, name='lists'),
]

plan_5x5x5/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('index.urls')),

    path('admin/', admin.site.urls),
]

index/models.py
from django.db import models


class Health(models.Model):

    name = models.CharField(max_length=10)

    replied = models.ForeignKey(
        'Health',
        on_delete=models.CASCADE,
        null=True,
    )


class FoodType(models.Model):
    name = models.CharField(max_length=20)


class Food(models.Model):

    name = models.CharField(max_length=128)

    health = models.ForeignKey(Health, on_delete=models.CASCADE)

    food_type = models.ForeignKey(FoodType, on_delete=models.CASCADE)

index/views.py
import random

from django.shortcuts import render

from .models import Health, Food, FoodType


def index(request):
    health_name = {}
    defense = {}

    healths = Health.objects.all()
    for health in healths:
        health_name[health.id] = health.name

        if Food.objects.filter(health_id=health.id).all():
            food = random.choice(Food.objects.filter(health_id=health.id).all())

            if health.replied_id:
                defense[health.replied_id]['value'][health.id] = {'name': health.name, 'value': food.name}
                pass
            else:
                defense[health.id] = {'name': health.name, 'value': food.name}

        else:
            defense[health.id] = {'name': health.name, 'value': {}}

    return render(request, 'index/index.html', {'defense': defense})


def lists(request, health_id):
    food_type = FoodType.objects.all()

    foods = Food.objects.filter(health_id=health_id).all().order_by('food_type')

    return render(request, 'index/list.html', {'food_type': list(food_type), 'foods': foods})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}5*5*5 Plan{% endblock %}</title>
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<body>
<main class="container">
    <header>
        <h1 class="text-center display-4">
            <a href="{% url 'index:index' %}" class="text-success"><strong>5*5*5 Plan</strong></a>
            <small class="text-muted sub-title">to the world</small>
        </h1>
    </header>
    {% block content %}{% endblock %}
    <footer class="text-center">
        {% block footer %}
            <small> &copy; 2021 <a href="http://greyli.com" title="Written by Grey Li">Grey Li</a> /
                <a href="https://github.com/greyli/sayhello" title="Fork me on GitHub">GitHub</a> /
                <a href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
            </small>
        {% endblock %}
    </footer>
</main>

<script type="text/javascript" src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/index/index.html
{% extends 'base.html' %}

{% load it %}

{% block content %}
    <div class="list-group">
        {% for k, v in defense.items %}
        {% if v.value|isdict %}
        {% for k1, v1 in v.value.items %}
            <a class="list-group-item list-group-item-action flex-column" href="{% url 'index:lists' k1 %}">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 text-success"> {{ v1.name }} </h5>
                    <small data-toggle="tooltip" data-placement="top"
                           data-timestamp=""
                           data-delay="500">
                    </small>
                </div>
                <p class="mb-1">{{ v1.value }}</p>
            </a>
        {% endfor %}
        {% else %}
            <a class="list-group-item list-group-item-action flex-column" href="{% url 'index:lists' k %}">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 text-success">{{ v.name }}</h5>
                    <small data-toggle="tooltip" data-placement="top"
                           data-timestamp=""
                           data-delay="500">
                    </small>
                </div>
                <p class="mb-1">{{ v.value }}</p>
            </a>
        {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/index/list.html
{% extends 'base.html' %}

{% load it %}

{% block content %}
    <div class="list-group">
    {% for type in food_type %}
        <a class="list-group-item list-group-item-action flex-column" href="#{{ type.id }}">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 text-primary">{{ type.name }}</h5>
                <small data-toggle="tooltip" data-placement="top"
                       data-timestamp=""
                       data-delay="500">
                </small>
            </div>
        </a>
    {% endfor %}
    {% for food in foods %}
    {% for type in food_type %}
    {% if food.food_type.id == type.id %}
        <a class="list-group-item list-group-item-action flex-column" id="{{ type.id }}">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 text-primary">{{ type.name }}</h5>
            </div>
        </a>
        {{ food_type|re:type }}
    {% endif %}
    {% endfor %}

        <a class="list-group-item list-group-item-action flex-column">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 text-success" onclick="copyTxt('{{ food.name }}')">{{ food.name }}</h5>
                <small data-toggle="tooltip" data-placement="top"
                       data-timestamp=""
                       data-delay="500">
                </small>
            </div>
            <p class="mb-1">{{ food.name }}</p>
        </a>
    {% endfor %}
    </div>
<script>
//原生js实现复制内容到剪切板，兼容pc、移动端（支持Safari浏览器）
function copyTxt(text){
    if(typeof document.execCommand!=="function"){
        alert("复制失败，请长按复制");
        return;
    }
    var dom = document.createElement("textarea");
    dom.value = text;
    dom.setAttribute('style', 'display: block;width: 1px;height: 1px;');
    document.body.appendChild(dom);
    dom.select();
    var result = document.execCommand('copy');
    document.body.removeChild(dom);
    if (result) {
        // alert("复制成功");
        return;
    }
    if(typeof document.createRange!=="function"){
        alert("复制失败，请长按复制");
        return;
    }
    var range = document.createRange();
    var div=document.createElement('div');
    div.innerhtml=text;
    div.setAttribute('style', 'height: 1px;fontSize: 1px;overflow: hidden;');
    document.body.appendChild(div);
    range.selectNode(div);
    const selection = window.getSelection();
    if (selection.rangeCount > 0){
        selection.removeAllRanges();
    }
    selection.addRange(range);
    document.execCommand('copy');
    // alert("复制成功")
}
</script>
{% endblock %}